apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend-deployment-bc-128
   labels:
      type: react-deployment
      app: fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        type: frontend
    spec:
      containers:
      - name: minet-frontend
        image: ghcr.io/paritosh-pranjal/bc128-fe-eks:v3
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                    - small
      imagePullSecrets: 
      - name: ghcr-secret