apiVersion: apps/v1
kind: Deployment
metadata:
   name: be-service-registry-deployment
   labels:
      type: service-registry-deployment
      app: backend-sr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: service-registry
  template:
    metadata:
      name: service-registry-pod
      labels:
        type: service-registry
    spec:
      containers:
      - name: bc128-backend-service-registry
        image: ghcr.io/paritosh-pranjal/bc128-be-eks-service-registry:v3
        ports:
        - containerPort: 8761
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                    - small
      imagePullSecrets: 
      - name: ghcr-secret
